version: '3.8'

services:
  cv_processor:
    build:
      context: ./cv-processor
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./cv-processor:/usr/src/app
    ports:
      - 3005:3005
    depends_on:
      - minio
      - redis
      - fakeSMTP
    env_file:
      - ./cv-processor/.env.docker
  cv_manager:
    build:
      context: ./cv-manager
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./cv-manager:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      minio:
        condition: service_started
      redis:
        condition: service_started
      cv_processor:
        condition: service_started
      db:
        condition: service_healthy
    links:
      - db
    env_file:
      - ./cv-manager/.env.docker
  